### ISSUE TITLE
Requiring credentials causes issue

### ISSUE THREAD

**Issue by jameswragg** [sholladay/scube#3]
Hi, I'd like to use this (more specifically hapi-s3) but the auth requirements causes the following error when I'm supplying the correct credentials[1]: `Uncaught InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

This is possibly down to having multiple profiles(?) all I know is if I comment out the `accessKeyId` & `secretAccessKey` in the Joi validation schema and the S3 constructor the AWS-SDK lib figures it out & works as expected.

Should the accesskey & secret be optional?

[1] if I debug the code I can see the accessKeyId and secretAccessKey are the same when when AWS-SDK figures out the credentials, so there must be something else loaded in the ini config that's not being used here, sessionToken?

**Comment by sholladay** [comment]
Hi James! I've always provided the credentials via environment variables and explicitly passed them in. I am aware that the SDK has some magic to load credentials from various places under the hood, though I'm not really familiar with profiles or how that all works and it's too implicit for my tastes.

That said, I think you're right that the explicit credentials should probably be optional here in this library, I just didn't write the validation with that use case in mind. A PR would be welcome.

One question: if you make the credentials optional in Scube, but then your profile is missing or has no credentials, what happens? Does the SDK throw when it is instantiated or does it fail silently until an API method is called?

Another thing worth considering is how credentials are handled in the new [AWS SDK v3](https://github.com/aws/aws-sdk-js-v3) package. I only found out about it a couple of days ago, but from what I can tell it's changing practically everything about how the SDK works. I thought I saw it mentioned somewhere that v3 doesn't implicitly load credentials but I couldn't quickly find a link to that.

**Comment by jameswragg** [comment]
Hi Seth, thanks for the quick response.

As far as I understand (and I'm no expert in these things) our infrastructure team use IAM Roles/EC2 meta data for credentials. They're cycled regularly, hence why I don't need to supply a key & secret. How the SDK resolves that internally I've no idea, perhaps as you say magic.

The AWS-SDK does throw its promises in error.

I'll try get a PR together to make the creds optional.

**Comment by sholladay** [comment]
Released in [v2.1.0](https://github.com/sholladay/scube/releases/tag/v2.1.0).

I decided on semver minor, so just reinstall your `hapi-s3` dependency and it should work. Let me know if you run into any problems.
